# For development
server:
  port: 8201
  error:
    whitelabel:
      enabled: false
    #key-store: classpath:springboot.p12
    #key-store-password: Epic@123
    #key-store-type: pkcs12
    #key-alias: springboot
    #key-password: Epic@123
#server:
#  port: 8200
#  address: 0.0.0.0
springdoc:
  swagger-ui:
    path: /swagger-ui.html
#Database configuration
spring:
  config:
    import: optional:configserver:http://localhost:8888

  mail:
    host: smtp.gmail.com
    port: 587
    username: acrsepic
    password: xrumtmvabhkqjqpu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  http:
    multipart:
      max-file-size: 5MB
      max-request-size:  5MB
  datasource:
    url: jdbc:mysql://124.43.16.185:50207/acrs_qa?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC &createDatabaseIfNotExists=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Ep1klanka@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-while-idle: true
    testOnBorrow: true
    validationQuery: SELECT 1
    hikari:
      minimumIdle: 2
      maximumPoolSize: 5
      idleTimeout: 350000
      maxLifetime: 400000
      connectionTimeout: 400000
      poolName: acr-main-pool

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _AUDIT
            revision_field_name: REVISION_ID
            revision_type_field_name: REVISION_TYPE
            #store_data_at_delete: true

  #liquibase
  liquibase:
    enabled: true
    default-schema: acrs_qa
    change-log: classpath:db/changelog/db.changelog.master.xml

jwt:
  token:
    expiration: 43200
    header: Authorization
    prefix: Bearer
    secret: MySecretKey
    uri: /authenticate

agent:
  token:
    expiration: 43200
    header: Authorization
    prefix: Bearer
    secret: MySecretKey
    uri: /agent/authenticate
module-name: ACRS Main module
api-version: 1.0
logging:
  level:
    com:
      zaxxer:
        hikari:
          HikariConfig: DEBUG
file:
  path:
    baseInputPath: /root/ACRS/files/Input
    baseOutputPath: /root/ACRS/files/Output
acrs:
  court:
    hours: 1
  security:
    time-gap: 15
    by-pass: 1
    ssl: 1
    https-age: 120
doxmate:
  base-url:  https://epictechdev.com:50231
  start-flow: /dwfservice/user-form/approve-work-flow-acrs
  update-flow: /dwfservice/user-form/update-work-flow-acrs
  tenant-id: 463
  x-tenant: acrst_6a01fc93-6d3a-3d51-840c-6f941e685fc7

application:
  name: main
  propertiesspring:
    cache:
      jcache:
        config: classpath:ehcache.xml

